# Generated by Django 4.2.3 on 2023-07-15 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_value', models.IntegerField(choices=[(1, 'Positive'), (-1, 'Negative')])),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lunch.employee')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lunch.menu')),
            ],
        ),
    ]
